// src/lib/constants.ts - adapted to Soleva
// Public contact details and prototype figures checked against soleva.org (September 2026).

export { SITE_URL } from "./site/constants";
export const SITE_NAME = "Soleva";

// CTAs point to the internal /contact page. No external booking URL.
export const CTA_DESTINATION = "/contact";

export const CONTACT = {
  businessName: "Soleva",
  fullName: "ASSOCIATION SOLEVA",
  phone: "+41 77 420 74 40",
  email: "info@soleva.org",
  ceoEmail: "curdin.wuethrich@soleva.org",
  address: {
    street: "Avenue de Cour 19",
    zip: "1007",
    city: "Lausanne",
    canton: "Vaud",
    country: "Suisse",
  },
  legalForm: "Association",
  IDE: "",
} as const;

export const SOCIALS = {
  instagram: "https://instagram.com/soleva_solar_van",
  facebook: "https://facebook.com/solevavan",
  linkedin: "https://www.linkedin.com/company/solevavanproject/",
  youtube: "https://youtube.com/channel/UCmw0pPduN1XgIyguDNtcv0w",
} as const;

export const THE_CORNER = {
  factoriesUrl: "https://the-corner.io/portfolio/forge",
  logoUrl: "https://assets.the-corner.io/logos/the_corner-icon.png",
} as const;

export const SITE = {
  faviconUrl: "/images/soleva-icon.webp",
} as const;

// All images served locally (migrated from Megaphone CDN - June 2026).
export const IMAGES = {
  hero: "/images/hero.webp",
  videoPoster: "/images/video-poster.webp",
  vanExterior: "/images/van-exterior.webp",
  vanInterior: "/images/van-interior.webp",
  solarPanels: "/images/solar-panels.webp",
  conversion: "/images/van-exterior.webp",
  habitat: "/images/habitat.webp",
  habitatHero: "/images/habitat-hero.webp",
  habitatInterior: "/images/habitat-interior.webp",
  habitatFeatures: "/images/habitat-features.webp",
  team: "/images/team.webp",
  workshop: "/images/workshop.webp",
  journey: "/images/journey.webp",
  impact: "/images/impact.webp",
  support: "/images/workshop.webp",
  newVanDesign: "/images/new-van-design.webp",
} as const;

// Responsive srcset candidates for the local images (generated by
// scripts/generate-image-variants.mjs - 480q90/800q80). Every entry ends with
// the ORIGINAL file as the top-width candidate so desktop/retina never get an
// upscaled variant (browsers pick the largest candidate, not `src`).
// Native widths: keep in sync with public/images/*.
const VARIANT_SRCSET: Record<string, string> = {
  [IMAGES.hero]: "/images/hero-480.webp 480w, /images/hero.webp 751w",
  [IMAGES.vanExterior]:
    "/images/van-exterior-480.webp 480w, /images/van-exterior-800.webp 800w, /images/van-exterior.webp 1200w",
  [IMAGES.solarPanels]:
    "/images/solar-panels-480.webp 480w, /images/solar-panels-800.webp 800w, /images/solar-panels.webp 917w",
  [IMAGES.habitat]:
    "/images/habitat-480.webp 480w, /images/habitat-800.webp 800w, /images/habitat.webp 801w",
  [IMAGES.habitatHero]:
    "/images/habitat-hero-480.webp 480w, /images/habitat-hero-800.webp 800w, /images/habitat-hero.webp 3840w",
  [IMAGES.habitatInterior]:
    "/images/habitat-interior-480.webp 480w, /images/habitat-interior-800.webp 800w, /images/habitat-interior.webp 2309w",
  [IMAGES.habitatFeatures]:
    "/images/habitat-features-480.webp 480w, /images/habitat-features-800.webp 800w, /images/habitat-features.webp 1896w",
  [IMAGES.journey]:
    "/images/journey-480.webp 480w, /images/journey-800.webp 800w, /images/journey.webp 1200w",
  [IMAGES.impact]:
    "/images/impact-480.webp 480w, /images/impact-800.webp 800w, /images/impact.webp 1250w",
  [IMAGES.workshop]:
    "/images/workshop-480.webp 480w, /images/workshop-800.webp 800w, /images/workshop.webp 1300w",
  [IMAGES.team]: "/images/team-480.webp 480w, /images/team-800.webp 800w, /images/team.webp 1200w",
  "/images/timeline.webp":
    "/images/timeline-480.webp 480w, /images/timeline-800.webp 800w, /images/timeline.webp 2010w",
  "/images/qr-code.webp":
    "/images/qr-code-480.webp 480w, /images/qr-code-800.webp 800w, /images/qr-code.webp 937w",
  "/images/new-van-design.webp":
    "/images/new-van-design-480.webp 480w, /images/new-van-design.webp 667w",
};

export function srcSetFor(src: string): string | undefined {
  return VARIANT_SRCSET[src];
}

// Partner logos
export const PARTNER_LOGOS = {
  csem: "/images/logos/csem.webp",
  epfl: "/images/logos/epfl.webp",
  studer: "/images/logos/studer.webp",
  brusa: "/images/logos/brusa.webp",
  cantonVaud: "/images/logos/canton-vaud.webp",
  sil: "/images/logos/sil.webp",
  energyLab: "/images/logos/energy-lab.webp",
} as const;

// Team member photos
export const TEAM_PHOTOS: Record<string, string> = {
  "Curdin Wüthrich": "/images/team/curdin.webp",
  "Matthieu Bourgois": "/images/team/matthieu.webp",
  "Max Chevron": "/images/team/max.webp",
  "Tobia Wyss": "/images/team/tobia.webp",
  "Sara Bossuyt": "/images/team/sara.webp",
  "Sévane Bercher": "/images/team/sevane.webp",
  "Lucanaël Kopf": "/images/team/lucanael.webp",
  "Roman Schmitz": "/images/team/roman.webp",
  "Nicola Offeddu": "/images/team/nicola.webp",
};

// Mentor photos
export const MENTOR_PHOTOS: Record<string, string> = {
  "Marc Müller": "/images/mentors/marc-muller.webp",
  "André Hodder": "/images/mentors/andre-hodder.webp",
  "Louis Palmer": "/images/mentors/louis-palmer.webp",
  "Prof. Dr. Werner Stednitz": "/images/mentors/werner-stednitz.webp",
};

// Press/media logos
export const PRESS_LOGOS: Record<string, string> = {
  "RTS 19h30": "/images/press/rts.webp",
  "SRF Schweiz Aktuell": "/images/press/srf.webp",
  "RSI Telegiornale": "/images/press/rsi.webp",
  "24Heures": "/images/press/24heures.webp",
  "Télé Vaud-Fribourg": "/images/press/tele-vaud-fribourg.webp",
  "RTS Radio Matinale": "/images/press/rts-radio.webp",
  "Rouge FM": "/images/press/rouge-fm.webp",
  LFM: "/images/press/lfm.webp",
  "La Côte": "/images/press/la-cote.webp",
};

// Published prototype specifications: /en/electric-conversion-van diagrams.
// The 250 km overview and >300 km at 80 km/h schematic use different conditions.
export const KEY_FIGURES = {
  foundedYear: 2021,
  crowdfundingAmount: "≈ CHF 30'000",
  crowdfundingBackers: "130+",
  crowdfundingPlatform: "Wemakeit",
  crowdfundingUrl: "https://wemakeit.com/projects/soleva-solar-electric-van",
  batteryCapacity: "58 kWh",
  autonomy: "~250 km",
  solarChargePerDay: "150 km",
  carbonReduction: "81%",
  vehicleOrigin: "Peugeot J9, 1987",
  solarPower: "5 kW",
} as const;

// TODO: Client must provide GA4 Measurement ID via NEXT_PUBLIC_GA_MEASUREMENT_ID.
export const COOKIE_CONSENT_KEY = "soleva-cookie-consent";

export const DONATION = {
  beneficiary: "ASSOCIATION SOLEVA",
  addressLine1: "Rue de Lausanne 64",
  addressLine2: "1020 Renens VD",
  iban: "CH3600767000L55322287",
  ibanFormatted: "CH36 0076 7000 L553 2228 7",
  bic: "BCVLCH2LXXX",
  bank: "Banque Cantonale Vaudoise",
  reference: "Donation au projet Soleva",
} as const;

export const HOSTING = {
  provider: "The Corner Factory SA",
  server: "Serveur VPS Infomaniak, Suisse",
} as const;
