export const employeeLabels = {
  title: "Employees",
  add: "Create User",
  name: "Name",
  email: "Email",
  password: "Temporary password",
  role: "Role",
  save: "Create User",
  adding: "Creating…",
  roleAdmin: "Admin",
  roleUser: "User",
  status: "Status",
  active: "Active",
  disabled: "Disabled",
  disable: "Disable access",
  enable: "Enable access",
  loading: "Loading employees…",
  error: "Could not load employees. Please try again.",
  createError:
    "Could not add this employee. Check the details and whether the email is already in use.",
  updateError: "Could not update access. Please try again.",
  empty: "No employees yet.",
  previous: "Previous",
  next: "Next",
  total: "employees",
  actions: "Actions",
  cancel: "Cancel",
  instructions:
    "Share the temporary password securely. The employee must change it when they first sign in.",
  verified: "Email verified",
  unverified: "Email not verified",
  sendEmail: "Send verification email to",
  emailSent: "Verification email sent.",
  emailUnavailable: "Email delivery is not set up. Contact your site administrator.",
  emailError: "Could not send the email. Please try again.",
  edit: "Edit",
  editTitle: "Edit user",
  editDescription: "Update the user’s details. Changing their email requires verification again.",
  editError: "Could not save changes. Check the details and whether the email is already in use.",
  saveChanges: "Save changes",
  saving: "Saving…",
  delete: "Delete",
  deleteTitle: "Delete user",
  deleteDescription:
    "Delete {name}? Their account and access will be permanently removed. This cannot be undone.",
  deleteError: "Could not delete this user. Please try again.",
  deleting: "Deleting…",
};
export type EmployeeLabels = typeof employeeLabels;
