/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthLangRouteImport } from './routes/_auth/$lang'
import { Route as SiteLangRouteImport } from './routes/_site/$lang'
import { Route as ApiDataDotjsonRouteImport } from './routes/api/data[.]json'
import { Route as AuthLangAppRouteRouteImport } from './routes/_auth/$lang/app/route'
import { Route as AuthLangLoginRouteImport } from './routes/_auth/$lang/login'
import { Route as AuthLangSignupRouteImport } from './routes/_auth/$lang/signup'
import { Route as SiteLangIndexRouteImport } from './routes/_site/$lang/index'
import { Route as SiteLangSplatRouteImport } from './routes/_site/$lang/$'
import { Route as SiteLangAProposRouteImport } from './routes/_site/$lang/a-propos'
import { Route as SiteLangConfidentialiteRouteImport } from './routes/_site/$lang/confidentialite'
import { Route as SiteLangContactRouteImport } from './routes/_site/$lang/contact'
import { Route as SiteLangFaqRouteImport } from './routes/_site/$lang/faq'
import { Route as SiteLangHabitatRouteImport } from './routes/_site/$lang/habitat'
import { Route as SiteLangImpactRouteImport } from './routes/_site/$lang/impact'
import { Route as SiteLangMentionsLegalesRouteImport } from './routes/_site/$lang/mentions-legales'
import { Route as SiteLangSoutenirRouteImport } from './routes/_site/$lang/soutenir'
import { Route as SiteLangVoyageRouteImport } from './routes/_site/$lang/voyage'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthLangAppIndexRouteImport } from './routes/_auth/$lang/app/index'
import { Route as SiteLangLeVanIndexRouteImport } from './routes/_site/$lang/le-van/index'
import { Route as SiteLangLeVanSlugRouteImport } from './routes/_site/$lang/le-van/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLangRoute = AuthLangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => AuthRouteRoute,
} as any)
const SiteLangRoute = SiteLangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => SiteRoute,
} as any)
const ApiDataDotjsonRoute = ApiDataDotjsonRouteImport.update({
  id: '/api/data.json',
  path: '/api/data.json',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLangAppRouteRoute = AuthLangAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthLangRoute,
} as any)
const AuthLangLoginRoute = AuthLangLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLangRoute,
} as any)
const AuthLangSignupRoute = AuthLangSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthLangRoute,
} as any)
const SiteLangIndexRoute = SiteLangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteLangRoute,
} as any)
const SiteLangSplatRoute = SiteLangSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SiteLangRoute,
} as any)
const SiteLangAProposRoute = SiteLangAProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => SiteLangRoute,
} as any)
const SiteLangConfidentialiteRoute = SiteLangConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => SiteLangRoute,
} as any)
const SiteLangContactRoute = SiteLangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteLangRoute,
} as any)
const SiteLangFaqRoute = SiteLangFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => SiteLangRoute,
} as any)
const SiteLangHabitatRoute = SiteLangHabitatRouteImport.update({
  id: '/habitat',
  path: '/habitat',
  getParentRoute: () => SiteLangRoute,
} as any)
const SiteLangImpactRoute = SiteLangImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => SiteLangRoute,
} as any)
const SiteLangMentionsLegalesRoute = SiteLangMentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => SiteLangRoute,
} as any)
const SiteLangSoutenirRoute = SiteLangSoutenirRouteImport.update({
  id: '/soutenir',
  path: '/soutenir',
  getParentRoute: () => SiteLangRoute,
} as any)
const SiteLangVoyageRoute = SiteLangVoyageRouteImport.update({
  id: '/voyage',
  path: '/voyage',
  getParentRoute: () => SiteLangRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLangAppIndexRoute = AuthLangAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthLangAppRouteRoute,
} as any)
const SiteLangLeVanIndexRoute = SiteLangLeVanIndexRouteImport.update({
  id: '/le-van/',
  path: '/le-van/',
  getParentRoute: () => SiteLangRoute,
} as any)
const SiteLangLeVanSlugRoute = SiteLangLeVanSlugRouteImport.update({
  id: '/le-van/$slug',
  path: '/le-van/$slug',
  getParentRoute: () => SiteLangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang': typeof SiteLangRouteWithChildren
  '/api/data.json': typeof ApiDataDotjsonRoute
  '/$lang/app': typeof AuthLangAppRouteRouteWithChildren
  '/$lang/login': typeof AuthLangLoginRoute
  '/$lang/signup': typeof AuthLangSignupRoute
  '/$lang/$': typeof SiteLangSplatRoute
  '/$lang/a-propos': typeof SiteLangAProposRoute
  '/$lang/confidentialite': typeof SiteLangConfidentialiteRoute
  '/$lang/contact': typeof SiteLangContactRoute
  '/$lang/faq': typeof SiteLangFaqRoute
  '/$lang/habitat': typeof SiteLangHabitatRoute
  '/$lang/impact': typeof SiteLangImpactRoute
  '/$lang/mentions-legales': typeof SiteLangMentionsLegalesRoute
  '/$lang/soutenir': typeof SiteLangSoutenirRoute
  '/$lang/voyage': typeof SiteLangVoyageRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$lang/': typeof SiteLangIndexRoute
  '/$lang/le-van/$slug': typeof SiteLangLeVanSlugRoute
  '/$lang/app/': typeof AuthLangAppIndexRoute
  '/$lang/le-van/': typeof SiteLangLeVanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang': typeof SiteLangIndexRoute
  '/api/data.json': typeof ApiDataDotjsonRoute
  '/$lang/login': typeof AuthLangLoginRoute
  '/$lang/signup': typeof AuthLangSignupRoute
  '/$lang/$': typeof SiteLangSplatRoute
  '/$lang/a-propos': typeof SiteLangAProposRoute
  '/$lang/confidentialite': typeof SiteLangConfidentialiteRoute
  '/$lang/contact': typeof SiteLangContactRoute
  '/$lang/faq': typeof SiteLangFaqRoute
  '/$lang/habitat': typeof SiteLangHabitatRoute
  '/$lang/impact': typeof SiteLangImpactRoute
  '/$lang/mentions-legales': typeof SiteLangMentionsLegalesRoute
  '/$lang/soutenir': typeof SiteLangSoutenirRoute
  '/$lang/voyage': typeof SiteLangVoyageRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$lang/le-van/$slug': typeof SiteLangLeVanSlugRoute
  '/$lang/app': typeof AuthLangAppIndexRoute
  '/$lang/le-van': typeof SiteLangLeVanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_auth/$lang': typeof AuthLangRouteWithChildren
  '/_site/$lang': typeof SiteLangRouteWithChildren
  '/api/data.json': typeof ApiDataDotjsonRoute
  '/_auth/$lang/app': typeof AuthLangAppRouteRouteWithChildren
  '/_auth/$lang/login': typeof AuthLangLoginRoute
  '/_auth/$lang/signup': typeof AuthLangSignupRoute
  '/_site/$lang/$': typeof SiteLangSplatRoute
  '/_site/$lang/a-propos': typeof SiteLangAProposRoute
  '/_site/$lang/confidentialite': typeof SiteLangConfidentialiteRoute
  '/_site/$lang/contact': typeof SiteLangContactRoute
  '/_site/$lang/faq': typeof SiteLangFaqRoute
  '/_site/$lang/habitat': typeof SiteLangHabitatRoute
  '/_site/$lang/impact': typeof SiteLangImpactRoute
  '/_site/$lang/mentions-legales': typeof SiteLangMentionsLegalesRoute
  '/_site/$lang/soutenir': typeof SiteLangSoutenirRoute
  '/_site/$lang/voyage': typeof SiteLangVoyageRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_site/$lang/': typeof SiteLangIndexRoute
  '/_site/$lang/le-van/$slug': typeof SiteLangLeVanSlugRoute
  '/_auth/$lang/app/': typeof AuthLangAppIndexRoute
  '/_site/$lang/le-van/': typeof SiteLangLeVanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$lang'
    | '/api/data.json'
    | '/$lang/app'
    | '/$lang/login'
    | '/$lang/signup'
    | '/$lang/$'
    | '/$lang/a-propos'
    | '/$lang/confidentialite'
    | '/$lang/contact'
    | '/$lang/faq'
    | '/$lang/habitat'
    | '/$lang/impact'
    | '/$lang/mentions-legales'
    | '/$lang/soutenir'
    | '/$lang/voyage'
    | '/api/auth/$'
    | '/$lang/'
    | '/$lang/le-van/$slug'
    | '/$lang/app/'
    | '/$lang/le-van/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$lang'
    | '/api/data.json'
    | '/$lang/login'
    | '/$lang/signup'
    | '/$lang/$'
    | '/$lang/a-propos'
    | '/$lang/confidentialite'
    | '/$lang/contact'
    | '/$lang/faq'
    | '/$lang/habitat'
    | '/$lang/impact'
    | '/$lang/mentions-legales'
    | '/$lang/soutenir'
    | '/$lang/voyage'
    | '/api/auth/$'
    | '/$lang/le-van/$slug'
    | '/$lang/app'
    | '/$lang/le-van'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_site'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_auth/$lang'
    | '/_site/$lang'
    | '/api/data.json'
    | '/_auth/$lang/app'
    | '/_auth/$lang/login'
    | '/_auth/$lang/signup'
    | '/_site/$lang/$'
    | '/_site/$lang/a-propos'
    | '/_site/$lang/confidentialite'
    | '/_site/$lang/contact'
    | '/_site/$lang/faq'
    | '/_site/$lang/habitat'
    | '/_site/$lang/impact'
    | '/_site/$lang/mentions-legales'
    | '/_site/$lang/soutenir'
    | '/_site/$lang/voyage'
    | '/api/auth/$'
    | '/_site/$lang/'
    | '/_site/$lang/le-van/$slug'
    | '/_auth/$lang/app/'
    | '/_site/$lang/le-van/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiDataDotjsonRoute: typeof ApiDataDotjsonRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/$lang': {
      id: '/_auth/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof AuthLangRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_site/$lang': {
      id: '/_site/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof SiteLangRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/data.json': {
      id: '/api/data.json'
      path: '/api/data.json'
      fullPath: '/api/data.json'
      preLoaderRoute: typeof ApiDataDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/$lang/app': {
      id: '/_auth/$lang/app'
      path: '/app'
      fullPath: '/$lang/app'
      preLoaderRoute: typeof AuthLangAppRouteRouteImport
      parentRoute: typeof AuthLangRoute
    }
    '/_auth/$lang/login': {
      id: '/_auth/$lang/login'
      path: '/login'
      fullPath: '/$lang/login'
      preLoaderRoute: typeof AuthLangLoginRouteImport
      parentRoute: typeof AuthLangRoute
    }
    '/_auth/$lang/signup': {
      id: '/_auth/$lang/signup'
      path: '/signup'
      fullPath: '/$lang/signup'
      preLoaderRoute: typeof AuthLangSignupRouteImport
      parentRoute: typeof AuthLangRoute
    }
    '/_site/$lang/': {
      id: '/_site/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof SiteLangIndexRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/_site/$lang/$': {
      id: '/_site/$lang/$'
      path: '/$'
      fullPath: '/$lang/$'
      preLoaderRoute: typeof SiteLangSplatRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/_site/$lang/a-propos': {
      id: '/_site/$lang/a-propos'
      path: '/a-propos'
      fullPath: '/$lang/a-propos'
      preLoaderRoute: typeof SiteLangAProposRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/_site/$lang/confidentialite': {
      id: '/_site/$lang/confidentialite'
      path: '/confidentialite'
      fullPath: '/$lang/confidentialite'
      preLoaderRoute: typeof SiteLangConfidentialiteRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/_site/$lang/contact': {
      id: '/_site/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof SiteLangContactRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/_site/$lang/faq': {
      id: '/_site/$lang/faq'
      path: '/faq'
      fullPath: '/$lang/faq'
      preLoaderRoute: typeof SiteLangFaqRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/_site/$lang/habitat': {
      id: '/_site/$lang/habitat'
      path: '/habitat'
      fullPath: '/$lang/habitat'
      preLoaderRoute: typeof SiteLangHabitatRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/_site/$lang/impact': {
      id: '/_site/$lang/impact'
      path: '/impact'
      fullPath: '/$lang/impact'
      preLoaderRoute: typeof SiteLangImpactRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/_site/$lang/mentions-legales': {
      id: '/_site/$lang/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/$lang/mentions-legales'
      preLoaderRoute: typeof SiteLangMentionsLegalesRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/_site/$lang/soutenir': {
      id: '/_site/$lang/soutenir'
      path: '/soutenir'
      fullPath: '/$lang/soutenir'
      preLoaderRoute: typeof SiteLangSoutenirRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/_site/$lang/voyage': {
      id: '/_site/$lang/voyage'
      path: '/voyage'
      fullPath: '/$lang/voyage'
      preLoaderRoute: typeof SiteLangVoyageRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/$lang/app/': {
      id: '/_auth/$lang/app/'
      path: '/'
      fullPath: '/$lang/app/'
      preLoaderRoute: typeof AuthLangAppIndexRouteImport
      parentRoute: typeof AuthLangAppRouteRoute
    }
    '/_site/$lang/le-van/': {
      id: '/_site/$lang/le-van/'
      path: '/le-van'
      fullPath: '/$lang/le-van/'
      preLoaderRoute: typeof SiteLangLeVanIndexRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/_site/$lang/le-van/$slug': {
      id: '/_site/$lang/le-van/$slug'
      path: '/le-van/$slug'
      fullPath: '/$lang/le-van/$slug'
      preLoaderRoute: typeof SiteLangLeVanSlugRouteImport
      parentRoute: typeof SiteLangRoute
    }
  }
}

interface AuthLangAppRouteRouteChildren {
  AuthLangAppIndexRoute: typeof AuthLangAppIndexRoute
}

const AuthLangAppRouteRouteChildren: AuthLangAppRouteRouteChildren = {
  AuthLangAppIndexRoute: AuthLangAppIndexRoute,
}

const AuthLangAppRouteRouteWithChildren =
  AuthLangAppRouteRoute._addFileChildren(AuthLangAppRouteRouteChildren)

interface AuthLangRouteChildren {
  AuthLangAppRouteRoute: typeof AuthLangAppRouteRouteWithChildren
  AuthLangLoginRoute: typeof AuthLangLoginRoute
  AuthLangSignupRoute: typeof AuthLangSignupRoute
}

const AuthLangRouteChildren: AuthLangRouteChildren = {
  AuthLangAppRouteRoute: AuthLangAppRouteRouteWithChildren,
  AuthLangLoginRoute: AuthLangLoginRoute,
  AuthLangSignupRoute: AuthLangSignupRoute,
}

const AuthLangRouteWithChildren = AuthLangRoute._addFileChildren(
  AuthLangRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLangRoute: typeof AuthLangRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLangRoute: AuthLangRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface SiteLangRouteChildren {
  SiteLangSplatRoute: typeof SiteLangSplatRoute
  SiteLangAProposRoute: typeof SiteLangAProposRoute
  SiteLangConfidentialiteRoute: typeof SiteLangConfidentialiteRoute
  SiteLangContactRoute: typeof SiteLangContactRoute
  SiteLangFaqRoute: typeof SiteLangFaqRoute
  SiteLangHabitatRoute: typeof SiteLangHabitatRoute
  SiteLangImpactRoute: typeof SiteLangImpactRoute
  SiteLangMentionsLegalesRoute: typeof SiteLangMentionsLegalesRoute
  SiteLangSoutenirRoute: typeof SiteLangSoutenirRoute
  SiteLangVoyageRoute: typeof SiteLangVoyageRoute
  SiteLangIndexRoute: typeof SiteLangIndexRoute
  SiteLangLeVanSlugRoute: typeof SiteLangLeVanSlugRoute
  SiteLangLeVanIndexRoute: typeof SiteLangLeVanIndexRoute
}

const SiteLangRouteChildren: SiteLangRouteChildren = {
  SiteLangSplatRoute: SiteLangSplatRoute,
  SiteLangAProposRoute: SiteLangAProposRoute,
  SiteLangConfidentialiteRoute: SiteLangConfidentialiteRoute,
  SiteLangContactRoute: SiteLangContactRoute,
  SiteLangFaqRoute: SiteLangFaqRoute,
  SiteLangHabitatRoute: SiteLangHabitatRoute,
  SiteLangImpactRoute: SiteLangImpactRoute,
  SiteLangMentionsLegalesRoute: SiteLangMentionsLegalesRoute,
  SiteLangSoutenirRoute: SiteLangSoutenirRoute,
  SiteLangVoyageRoute: SiteLangVoyageRoute,
  SiteLangIndexRoute: SiteLangIndexRoute,
  SiteLangLeVanSlugRoute: SiteLangLeVanSlugRoute,
  SiteLangLeVanIndexRoute: SiteLangLeVanIndexRoute,
}

const SiteLangRouteWithChildren = SiteLangRoute._addFileChildren(
  SiteLangRouteChildren,
)

interface SiteRouteChildren {
  SiteLangRoute: typeof SiteLangRouteWithChildren
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteLangRoute: SiteLangRouteWithChildren,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  LlmsDottxtRoute: LlmsDottxtRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiDataDotjsonRoute: ApiDataDotjsonRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
