/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './intranet/routes/_auth/route'
import { Route as GuestRouteRouteImport } from './intranet/routes/_guest/route'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as LlmsChar91DotChar93txtRouteImport } from './routes/llms[.]txt'
import { Route as RobotsChar91DotChar93txtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapChar91DotChar93xmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthLangRouteImport } from './intranet/routes/_auth/$lang'
import { Route as GuestAppRouteImport } from './intranet/routes/_guest/app'
import { Route as GuestIntranetRouteImport } from './intranet/routes/_guest/intranet'
import { Route as GuestLoginRouteImport } from './intranet/routes/_guest/login'
import { Route as SiteLangRouteImport } from './routes/_site/$lang'
import { Route as ApiDataChar91DotChar93jsonRouteImport } from './routes/api/data[.]json'
import { Route as AuthLangAccessDeniedRouteImport } from './intranet/routes/_auth/$lang/access-denied'
import { Route as AuthLangAppRouteImport } from './intranet/routes/_auth/$lang/app'
import { Route as AuthLangChangePasswordRouteImport } from './intranet/routes/_auth/$lang/change-password'
import { Route as AuthLangForgotPasswordRouteImport } from './intranet/routes/_auth/$lang/forgot-password'
import { Route as AuthLangIntranetRouteRouteImport } from './intranet/routes/_auth/$lang/intranet/route'
import { Route as AuthLangLoginRouteImport } from './intranet/routes/_auth/$lang/login'
import { Route as AuthLangResetPasswordRouteImport } from './intranet/routes/_auth/$lang/reset-password'
import { Route as SiteLangIndexRouteImport } from './routes/_site/$lang/index'
import { Route as SiteLangSplatRouteImport } from './routes/_site/$lang/$'
import { Route as SiteLangAProposRouteImport } from './routes/_site/$lang/a-propos'
import { Route as SiteLangBlogRouteImport } from './routes/_site/$lang/blog'
import { Route as SiteLangConfidentialiteRouteImport } from './routes/_site/$lang/confidentialite'
import { Route as SiteLangContactRouteImport } from './routes/_site/$lang/contact'
import { Route as SiteLangCrowdfundingRouteImport } from './routes/_site/$lang/crowdfunding'
import { Route as SiteLangEquipeRouteImport } from './routes/_site/$lang/equipe'
import { Route as SiteLangEvenementsRouteImport } from './routes/_site/$lang/evenements'
import { Route as SiteLangFaqRouteImport } from './routes/_site/$lang/faq'
import { Route as SiteLangHabitatRouteImport } from './routes/_site/$lang/habitat'
import { Route as SiteLangImpactRouteImport } from './routes/_site/$lang/impact'
import { Route as SiteLangMentionsLegalesRouteImport } from './routes/_site/$lang/mentions-legales'
import { Route as SiteLangPartenairesRouteImport } from './routes/_site/$lang/partenaires'
import { Route as SiteLangPlanDuSiteRouteImport } from './routes/_site/$lang/plan-du-site'
import { Route as SiteLangPresseRouteImport } from './routes/_site/$lang/presse'
import { Route as SiteLangSoutenirRouteImport } from './routes/_site/$lang/soutenir'
import { Route as SiteLangSponsoringRouteImport } from './routes/_site/$lang/sponsoring'
import { Route as SiteLangVoyageRouteImport } from './routes/_site/$lang/voyage'
import { Route as ApiAuthSplatRouteImport } from './intranet/routes/api/auth/$'
import { Route as AuthLangIntranetIndexRouteImport } from './intranet/routes/_auth/$lang/intranet/index'
import { Route as SiteLangLeVanIndexRouteImport } from './routes/_site/$lang/le-van/index'
import { Route as SiteLangLeVanSlugRouteImport } from './routes/_site/$lang/le-van/$slug'
import { Route as AuthLangIntranetEmployeesIndexRouteImport } from './intranet/routes/_auth/$lang/intranet/employees/index'
import { Route as AuthLangIntranetEmployeesNewRouteImport } from './intranet/routes/_auth/$lang/intranet/employees/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsChar91DotChar93txtRoute = LlmsChar91DotChar93txtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsChar91DotChar93txtRoute =
  RobotsChar91DotChar93txtRouteImport.update({
    id: '/robots.txt',
    path: '/robots.txt',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapChar91DotChar93xmlRoute =
  SitemapChar91DotChar93xmlRouteImport.update({
    id: '/sitemap.xml',
    path: '/sitemap.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthLangRoute = AuthLangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => AuthRouteRoute,
} as any)
const GuestAppRoute = GuestAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestIntranetRoute = GuestIntranetRouteImport.update({
  id: '/intranet',
  path: '/intranet',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const SiteLangRoute = SiteLangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => SiteRoute,
} as any)
const ApiDataChar91DotChar93jsonRoute =
  ApiDataChar91DotChar93jsonRouteImport.update({
    id: '/api/data.json',
    path: '/api/data.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthLangAccessDeniedRoute = AuthLangAccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => AuthLangRoute,
} as any)
const AuthLangAppRoute = AuthLangAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthLangRoute,
} as any)
const AuthLangChangePasswordRoute = AuthLangChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AuthLangRoute,
} as any)
const AuthLangForgotPasswordRoute = AuthLangForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthLangRoute,
} as any)
const AuthLangIntranetRouteRoute = AuthLangIntranetRouteRouteImport.update({
  id: '/intranet',
  path: '/intranet',
  getParentRoute: () => AuthLangRoute,
} as any)
const AuthLangLoginRoute = AuthLangLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLangRoute,
} as any)
const AuthLangResetPasswordRoute = AuthLangResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthLangRoute,
} as any)
const SiteLangIndexRoute = SiteLangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteLangRoute,
} as any)
const SiteLangSplatRoute = SiteLangSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SiteLangRoute,
} as any)
const SiteLangAProposRoute = SiteLangAProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => SiteLangRoute,
} as any)
const SiteLangBlogRoute = SiteLangBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => SiteLangRoute,
} as any)
const SiteLangConfidentialiteRoute = SiteLangConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => SiteLangRoute,
} as any)
const SiteLangContactRoute = SiteLangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteLangRoute,
} as any)
const SiteLangCrowdfundingRoute = SiteLangCrowdfundingRouteImport.update({
  id: '/crowdfunding',
  path: '/crowdfunding',
  getParentRoute: () => SiteLangRoute,
} as any)
const SiteLangEquipeRoute = SiteLangEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => SiteLangRoute,
} as any)
const SiteLangEvenementsRoute = SiteLangEvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => SiteLangRoute,
} as any)
const SiteLangFaqRoute = SiteLangFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => SiteLangRoute,
} as any)
const SiteLangHabitatRoute = SiteLangHabitatRouteImport.update({
  id: '/habitat',
  path: '/habitat',
  getParentRoute: () => SiteLangRoute,
} as any)
const SiteLangImpactRoute = SiteLangImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => SiteLangRoute,
} as any)
const SiteLangMentionsLegalesRoute = SiteLangMentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => SiteLangRoute,
} as any)
const SiteLangPartenairesRoute = SiteLangPartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => SiteLangRoute,
} as any)
const SiteLangPlanDuSiteRoute = SiteLangPlanDuSiteRouteImport.update({
  id: '/plan-du-site',
  path: '/plan-du-site',
  getParentRoute: () => SiteLangRoute,
} as any)
const SiteLangPresseRoute = SiteLangPresseRouteImport.update({
  id: '/presse',
  path: '/presse',
  getParentRoute: () => SiteLangRoute,
} as any)
const SiteLangSoutenirRoute = SiteLangSoutenirRouteImport.update({
  id: '/soutenir',
  path: '/soutenir',
  getParentRoute: () => SiteLangRoute,
} as any)
const SiteLangSponsoringRoute = SiteLangSponsoringRouteImport.update({
  id: '/sponsoring',
  path: '/sponsoring',
  getParentRoute: () => SiteLangRoute,
} as any)
const SiteLangVoyageRoute = SiteLangVoyageRouteImport.update({
  id: '/voyage',
  path: '/voyage',
  getParentRoute: () => SiteLangRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLangIntranetIndexRoute = AuthLangIntranetIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthLangIntranetRouteRoute,
} as any)
const SiteLangLeVanIndexRoute = SiteLangLeVanIndexRouteImport.update({
  id: '/le-van/',
  path: '/le-van/',
  getParentRoute: () => SiteLangRoute,
} as any)
const SiteLangLeVanSlugRoute = SiteLangLeVanSlugRouteImport.update({
  id: '/le-van/$slug',
  path: '/le-van/$slug',
  getParentRoute: () => SiteLangRoute,
} as any)
const AuthLangIntranetEmployeesIndexRoute =
  AuthLangIntranetEmployeesIndexRouteImport.update({
    id: '/employees/',
    path: '/employees/',
    getParentRoute: () => AuthLangIntranetRouteRoute,
  } as any)
const AuthLangIntranetEmployeesNewRoute =
  AuthLangIntranetEmployeesNewRouteImport.update({
    id: '/employees/new',
    path: '/employees/new',
    getParentRoute: () => AuthLangIntranetRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsChar91DotChar93txtRoute
  '/robots.txt': typeof RobotsChar91DotChar93txtRoute
  '/sitemap.xml': typeof SitemapChar91DotChar93xmlRoute
  '/$lang': typeof SiteLangRouteWithChildren
  '/app': typeof GuestAppRoute
  '/intranet': typeof GuestIntranetRoute
  '/login': typeof GuestLoginRoute
  '/api/data.json': typeof ApiDataChar91DotChar93jsonRoute
  '/$lang/intranet': typeof AuthLangIntranetRouteRouteWithChildren
  '/$lang/access-denied': typeof AuthLangAccessDeniedRoute
  '/$lang/app': typeof AuthLangAppRoute
  '/$lang/change-password': typeof AuthLangChangePasswordRoute
  '/$lang/forgot-password': typeof AuthLangForgotPasswordRoute
  '/$lang/login': typeof AuthLangLoginRoute
  '/$lang/reset-password': typeof AuthLangResetPasswordRoute
  '/$lang/$': typeof SiteLangSplatRoute
  '/$lang/a-propos': typeof SiteLangAProposRoute
  '/$lang/blog': typeof SiteLangBlogRoute
  '/$lang/confidentialite': typeof SiteLangConfidentialiteRoute
  '/$lang/contact': typeof SiteLangContactRoute
  '/$lang/crowdfunding': typeof SiteLangCrowdfundingRoute
  '/$lang/equipe': typeof SiteLangEquipeRoute
  '/$lang/evenements': typeof SiteLangEvenementsRoute
  '/$lang/faq': typeof SiteLangFaqRoute
  '/$lang/habitat': typeof SiteLangHabitatRoute
  '/$lang/impact': typeof SiteLangImpactRoute
  '/$lang/mentions-legales': typeof SiteLangMentionsLegalesRoute
  '/$lang/partenaires': typeof SiteLangPartenairesRoute
  '/$lang/plan-du-site': typeof SiteLangPlanDuSiteRoute
  '/$lang/presse': typeof SiteLangPresseRoute
  '/$lang/soutenir': typeof SiteLangSoutenirRoute
  '/$lang/sponsoring': typeof SiteLangSponsoringRoute
  '/$lang/voyage': typeof SiteLangVoyageRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$lang/': typeof SiteLangIndexRoute
  '/$lang/le-van/$slug': typeof SiteLangLeVanSlugRoute
  '/$lang/intranet/': typeof AuthLangIntranetIndexRoute
  '/$lang/le-van/': typeof SiteLangLeVanIndexRoute
  '/$lang/intranet/employees/new': typeof AuthLangIntranetEmployeesNewRoute
  '/$lang/intranet/employees/': typeof AuthLangIntranetEmployeesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsChar91DotChar93txtRoute
  '/robots.txt': typeof RobotsChar91DotChar93txtRoute
  '/sitemap.xml': typeof SitemapChar91DotChar93xmlRoute
  '/$lang': typeof SiteLangIndexRoute
  '/app': typeof GuestAppRoute
  '/intranet': typeof GuestIntranetRoute
  '/login': typeof GuestLoginRoute
  '/api/data.json': typeof ApiDataChar91DotChar93jsonRoute
  '/$lang/access-denied': typeof AuthLangAccessDeniedRoute
  '/$lang/app': typeof AuthLangAppRoute
  '/$lang/change-password': typeof AuthLangChangePasswordRoute
  '/$lang/forgot-password': typeof AuthLangForgotPasswordRoute
  '/$lang/login': typeof AuthLangLoginRoute
  '/$lang/reset-password': typeof AuthLangResetPasswordRoute
  '/$lang/$': typeof SiteLangSplatRoute
  '/$lang/a-propos': typeof SiteLangAProposRoute
  '/$lang/blog': typeof SiteLangBlogRoute
  '/$lang/confidentialite': typeof SiteLangConfidentialiteRoute
  '/$lang/contact': typeof SiteLangContactRoute
  '/$lang/crowdfunding': typeof SiteLangCrowdfundingRoute
  '/$lang/equipe': typeof SiteLangEquipeRoute
  '/$lang/evenements': typeof SiteLangEvenementsRoute
  '/$lang/faq': typeof SiteLangFaqRoute
  '/$lang/habitat': typeof SiteLangHabitatRoute
  '/$lang/impact': typeof SiteLangImpactRoute
  '/$lang/mentions-legales': typeof SiteLangMentionsLegalesRoute
  '/$lang/partenaires': typeof SiteLangPartenairesRoute
  '/$lang/plan-du-site': typeof SiteLangPlanDuSiteRoute
  '/$lang/presse': typeof SiteLangPresseRoute
  '/$lang/soutenir': typeof SiteLangSoutenirRoute
  '/$lang/sponsoring': typeof SiteLangSponsoringRoute
  '/$lang/voyage': typeof SiteLangVoyageRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$lang/le-van/$slug': typeof SiteLangLeVanSlugRoute
  '/$lang/intranet': typeof AuthLangIntranetIndexRoute
  '/$lang/le-van': typeof SiteLangLeVanIndexRoute
  '/$lang/intranet/employees/new': typeof AuthLangIntranetEmployeesNewRoute
  '/$lang/intranet/employees': typeof AuthLangIntranetEmployeesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/llms.txt': typeof LlmsChar91DotChar93txtRoute
  '/robots.txt': typeof RobotsChar91DotChar93txtRoute
  '/sitemap.xml': typeof SitemapChar91DotChar93xmlRoute
  '/_auth/$lang': typeof AuthLangRouteWithChildren
  '/_guest/app': typeof GuestAppRoute
  '/_guest/intranet': typeof GuestIntranetRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_site/$lang': typeof SiteLangRouteWithChildren
  '/api/data.json': typeof ApiDataChar91DotChar93jsonRoute
  '/_auth/$lang/intranet': typeof AuthLangIntranetRouteRouteWithChildren
  '/_auth/$lang/access-denied': typeof AuthLangAccessDeniedRoute
  '/_auth/$lang/app': typeof AuthLangAppRoute
  '/_auth/$lang/change-password': typeof AuthLangChangePasswordRoute
  '/_auth/$lang/forgot-password': typeof AuthLangForgotPasswordRoute
  '/_auth/$lang/login': typeof AuthLangLoginRoute
  '/_auth/$lang/reset-password': typeof AuthLangResetPasswordRoute
  '/_site/$lang/$': typeof SiteLangSplatRoute
  '/_site/$lang/a-propos': typeof SiteLangAProposRoute
  '/_site/$lang/blog': typeof SiteLangBlogRoute
  '/_site/$lang/confidentialite': typeof SiteLangConfidentialiteRoute
  '/_site/$lang/contact': typeof SiteLangContactRoute
  '/_site/$lang/crowdfunding': typeof SiteLangCrowdfundingRoute
  '/_site/$lang/equipe': typeof SiteLangEquipeRoute
  '/_site/$lang/evenements': typeof SiteLangEvenementsRoute
  '/_site/$lang/faq': typeof SiteLangFaqRoute
  '/_site/$lang/habitat': typeof SiteLangHabitatRoute
  '/_site/$lang/impact': typeof SiteLangImpactRoute
  '/_site/$lang/mentions-legales': typeof SiteLangMentionsLegalesRoute
  '/_site/$lang/partenaires': typeof SiteLangPartenairesRoute
  '/_site/$lang/plan-du-site': typeof SiteLangPlanDuSiteRoute
  '/_site/$lang/presse': typeof SiteLangPresseRoute
  '/_site/$lang/soutenir': typeof SiteLangSoutenirRoute
  '/_site/$lang/sponsoring': typeof SiteLangSponsoringRoute
  '/_site/$lang/voyage': typeof SiteLangVoyageRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_site/$lang/': typeof SiteLangIndexRoute
  '/_site/$lang/le-van/$slug': typeof SiteLangLeVanSlugRoute
  '/_auth/$lang/intranet/': typeof AuthLangIntranetIndexRoute
  '/_site/$lang/le-van/': typeof SiteLangLeVanIndexRoute
  '/_auth/$lang/intranet/employees/new': typeof AuthLangIntranetEmployeesNewRoute
  '/_auth/$lang/intranet/employees/': typeof AuthLangIntranetEmployeesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$lang'
    | '/app'
    | '/intranet'
    | '/login'
    | '/api/data.json'
    | '/$lang/intranet'
    | '/$lang/access-denied'
    | '/$lang/app'
    | '/$lang/change-password'
    | '/$lang/forgot-password'
    | '/$lang/login'
    | '/$lang/reset-password'
    | '/$lang/$'
    | '/$lang/a-propos'
    | '/$lang/blog'
    | '/$lang/confidentialite'
    | '/$lang/contact'
    | '/$lang/crowdfunding'
    | '/$lang/equipe'
    | '/$lang/evenements'
    | '/$lang/faq'
    | '/$lang/habitat'
    | '/$lang/impact'
    | '/$lang/mentions-legales'
    | '/$lang/partenaires'
    | '/$lang/plan-du-site'
    | '/$lang/presse'
    | '/$lang/soutenir'
    | '/$lang/sponsoring'
    | '/$lang/voyage'
    | '/api/auth/$'
    | '/$lang/'
    | '/$lang/le-van/$slug'
    | '/$lang/intranet/'
    | '/$lang/le-van/'
    | '/$lang/intranet/employees/new'
    | '/$lang/intranet/employees/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$lang'
    | '/app'
    | '/intranet'
    | '/login'
    | '/api/data.json'
    | '/$lang/access-denied'
    | '/$lang/app'
    | '/$lang/change-password'
    | '/$lang/forgot-password'
    | '/$lang/login'
    | '/$lang/reset-password'
    | '/$lang/$'
    | '/$lang/a-propos'
    | '/$lang/blog'
    | '/$lang/confidentialite'
    | '/$lang/contact'
    | '/$lang/crowdfunding'
    | '/$lang/equipe'
    | '/$lang/evenements'
    | '/$lang/faq'
    | '/$lang/habitat'
    | '/$lang/impact'
    | '/$lang/mentions-legales'
    | '/$lang/partenaires'
    | '/$lang/plan-du-site'
    | '/$lang/presse'
    | '/$lang/soutenir'
    | '/$lang/sponsoring'
    | '/$lang/voyage'
    | '/api/auth/$'
    | '/$lang/le-van/$slug'
    | '/$lang/intranet'
    | '/$lang/le-van'
    | '/$lang/intranet/employees/new'
    | '/$lang/intranet/employees'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/_site'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_auth/$lang'
    | '/_guest/app'
    | '/_guest/intranet'
    | '/_guest/login'
    | '/_site/$lang'
    | '/api/data.json'
    | '/_auth/$lang/intranet'
    | '/_auth/$lang/access-denied'
    | '/_auth/$lang/app'
    | '/_auth/$lang/change-password'
    | '/_auth/$lang/forgot-password'
    | '/_auth/$lang/login'
    | '/_auth/$lang/reset-password'
    | '/_site/$lang/$'
    | '/_site/$lang/a-propos'
    | '/_site/$lang/blog'
    | '/_site/$lang/confidentialite'
    | '/_site/$lang/contact'
    | '/_site/$lang/crowdfunding'
    | '/_site/$lang/equipe'
    | '/_site/$lang/evenements'
    | '/_site/$lang/faq'
    | '/_site/$lang/habitat'
    | '/_site/$lang/impact'
    | '/_site/$lang/mentions-legales'
    | '/_site/$lang/partenaires'
    | '/_site/$lang/plan-du-site'
    | '/_site/$lang/presse'
    | '/_site/$lang/soutenir'
    | '/_site/$lang/sponsoring'
    | '/_site/$lang/voyage'
    | '/api/auth/$'
    | '/_site/$lang/'
    | '/_site/$lang/le-van/$slug'
    | '/_auth/$lang/intranet/'
    | '/_site/$lang/le-van/'
    | '/_auth/$lang/intranet/employees/new'
    | '/_auth/$lang/intranet/employees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  LlmsChar91DotChar93txtRoute: typeof LlmsChar91DotChar93txtRoute
  RobotsChar91DotChar93txtRoute: typeof RobotsChar91DotChar93txtRoute
  SitemapChar91DotChar93xmlRoute: typeof SitemapChar91DotChar93xmlRoute
  ApiDataChar91DotChar93jsonRoute: typeof ApiDataChar91DotChar93jsonRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsChar91DotChar93txtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsChar91DotChar93txtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapChar91DotChar93xmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/$lang': {
      id: '/_auth/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof AuthLangRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_guest/app': {
      id: '/_guest/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof GuestAppRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/intranet': {
      id: '/_guest/intranet'
      path: '/intranet'
      fullPath: '/intranet'
      preLoaderRoute: typeof GuestIntranetRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_site/$lang': {
      id: '/_site/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof SiteLangRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/data.json': {
      id: '/api/data.json'
      path: '/api/data.json'
      fullPath: '/api/data.json'
      preLoaderRoute: typeof ApiDataChar91DotChar93jsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/$lang/access-denied': {
      id: '/_auth/$lang/access-denied'
      path: '/access-denied'
      fullPath: '/$lang/access-denied'
      preLoaderRoute: typeof AuthLangAccessDeniedRouteImport
      parentRoute: typeof AuthLangRoute
    }
    '/_auth/$lang/app': {
      id: '/_auth/$lang/app'
      path: '/app'
      fullPath: '/$lang/app'
      preLoaderRoute: typeof AuthLangAppRouteImport
      parentRoute: typeof AuthLangRoute
    }
    '/_auth/$lang/change-password': {
      id: '/_auth/$lang/change-password'
      path: '/change-password'
      fullPath: '/$lang/change-password'
      preLoaderRoute: typeof AuthLangChangePasswordRouteImport
      parentRoute: typeof AuthLangRoute
    }
    '/_auth/$lang/forgot-password': {
      id: '/_auth/$lang/forgot-password'
      path: '/forgot-password'
      fullPath: '/$lang/forgot-password'
      preLoaderRoute: typeof AuthLangForgotPasswordRouteImport
      parentRoute: typeof AuthLangRoute
    }
    '/_auth/$lang/intranet': {
      id: '/_auth/$lang/intranet'
      path: '/intranet'
      fullPath: '/$lang/intranet'
      preLoaderRoute: typeof AuthLangIntranetRouteRouteImport
      parentRoute: typeof AuthLangRoute
    }
    '/_auth/$lang/login': {
      id: '/_auth/$lang/login'
      path: '/login'
      fullPath: '/$lang/login'
      preLoaderRoute: typeof AuthLangLoginRouteImport
      parentRoute: typeof AuthLangRoute
    }
    '/_auth/$lang/reset-password': {
      id: '/_auth/$lang/reset-password'
      path: '/reset-password'
      fullPath: '/$lang/reset-password'
      preLoaderRoute: typeof AuthLangResetPasswordRouteImport
      parentRoute: typeof AuthLangRoute
    }
    '/_site/$lang/': {
      id: '/_site/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof SiteLangIndexRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/_site/$lang/$': {
      id: '/_site/$lang/$'
      path: '/$'
      fullPath: '/$lang/$'
      preLoaderRoute: typeof SiteLangSplatRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/_site/$lang/a-propos': {
      id: '/_site/$lang/a-propos'
      path: '/a-propos'
      fullPath: '/$lang/a-propos'
      preLoaderRoute: typeof SiteLangAProposRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/_site/$lang/blog': {
      id: '/_site/$lang/blog'
      path: '/blog'
      fullPath: '/$lang/blog'
      preLoaderRoute: typeof SiteLangBlogRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/_site/$lang/confidentialite': {
      id: '/_site/$lang/confidentialite'
      path: '/confidentialite'
      fullPath: '/$lang/confidentialite'
      preLoaderRoute: typeof SiteLangConfidentialiteRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/_site/$lang/contact': {
      id: '/_site/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof SiteLangContactRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/_site/$lang/crowdfunding': {
      id: '/_site/$lang/crowdfunding'
      path: '/crowdfunding'
      fullPath: '/$lang/crowdfunding'
      preLoaderRoute: typeof SiteLangCrowdfundingRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/_site/$lang/equipe': {
      id: '/_site/$lang/equipe'
      path: '/equipe'
      fullPath: '/$lang/equipe'
      preLoaderRoute: typeof SiteLangEquipeRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/_site/$lang/evenements': {
      id: '/_site/$lang/evenements'
      path: '/evenements'
      fullPath: '/$lang/evenements'
      preLoaderRoute: typeof SiteLangEvenementsRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/_site/$lang/faq': {
      id: '/_site/$lang/faq'
      path: '/faq'
      fullPath: '/$lang/faq'
      preLoaderRoute: typeof SiteLangFaqRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/_site/$lang/habitat': {
      id: '/_site/$lang/habitat'
      path: '/habitat'
      fullPath: '/$lang/habitat'
      preLoaderRoute: typeof SiteLangHabitatRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/_site/$lang/impact': {
      id: '/_site/$lang/impact'
      path: '/impact'
      fullPath: '/$lang/impact'
      preLoaderRoute: typeof SiteLangImpactRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/_site/$lang/mentions-legales': {
      id: '/_site/$lang/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/$lang/mentions-legales'
      preLoaderRoute: typeof SiteLangMentionsLegalesRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/_site/$lang/partenaires': {
      id: '/_site/$lang/partenaires'
      path: '/partenaires'
      fullPath: '/$lang/partenaires'
      preLoaderRoute: typeof SiteLangPartenairesRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/_site/$lang/plan-du-site': {
      id: '/_site/$lang/plan-du-site'
      path: '/plan-du-site'
      fullPath: '/$lang/plan-du-site'
      preLoaderRoute: typeof SiteLangPlanDuSiteRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/_site/$lang/presse': {
      id: '/_site/$lang/presse'
      path: '/presse'
      fullPath: '/$lang/presse'
      preLoaderRoute: typeof SiteLangPresseRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/_site/$lang/soutenir': {
      id: '/_site/$lang/soutenir'
      path: '/soutenir'
      fullPath: '/$lang/soutenir'
      preLoaderRoute: typeof SiteLangSoutenirRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/_site/$lang/sponsoring': {
      id: '/_site/$lang/sponsoring'
      path: '/sponsoring'
      fullPath: '/$lang/sponsoring'
      preLoaderRoute: typeof SiteLangSponsoringRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/_site/$lang/voyage': {
      id: '/_site/$lang/voyage'
      path: '/voyage'
      fullPath: '/$lang/voyage'
      preLoaderRoute: typeof SiteLangVoyageRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/$lang/intranet/': {
      id: '/_auth/$lang/intranet/'
      path: '/'
      fullPath: '/$lang/intranet/'
      preLoaderRoute: typeof AuthLangIntranetIndexRouteImport
      parentRoute: typeof AuthLangIntranetRouteRoute
    }
    '/_site/$lang/le-van/': {
      id: '/_site/$lang/le-van/'
      path: '/le-van'
      fullPath: '/$lang/le-van/'
      preLoaderRoute: typeof SiteLangLeVanIndexRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/_site/$lang/le-van/$slug': {
      id: '/_site/$lang/le-van/$slug'
      path: '/le-van/$slug'
      fullPath: '/$lang/le-van/$slug'
      preLoaderRoute: typeof SiteLangLeVanSlugRouteImport
      parentRoute: typeof SiteLangRoute
    }
    '/_auth/$lang/intranet/employees/': {
      id: '/_auth/$lang/intranet/employees/'
      path: '/employees'
      fullPath: '/$lang/intranet/employees/'
      preLoaderRoute: typeof AuthLangIntranetEmployeesIndexRouteImport
      parentRoute: typeof AuthLangIntranetRouteRoute
    }
    '/_auth/$lang/intranet/employees/new': {
      id: '/_auth/$lang/intranet/employees/new'
      path: '/employees/new'
      fullPath: '/$lang/intranet/employees/new'
      preLoaderRoute: typeof AuthLangIntranetEmployeesNewRouteImport
      parentRoute: typeof AuthLangIntranetRouteRoute
    }
  }
}

interface AuthLangIntranetRouteRouteChildren {
  AuthLangIntranetIndexRoute: typeof AuthLangIntranetIndexRoute
  AuthLangIntranetEmployeesNewRoute: typeof AuthLangIntranetEmployeesNewRoute
  AuthLangIntranetEmployeesIndexRoute: typeof AuthLangIntranetEmployeesIndexRoute
}

const AuthLangIntranetRouteRouteChildren: AuthLangIntranetRouteRouteChildren = {
  AuthLangIntranetIndexRoute: AuthLangIntranetIndexRoute,
  AuthLangIntranetEmployeesNewRoute: AuthLangIntranetEmployeesNewRoute,
  AuthLangIntranetEmployeesIndexRoute: AuthLangIntranetEmployeesIndexRoute,
}

const AuthLangIntranetRouteRouteWithChildren =
  AuthLangIntranetRouteRoute._addFileChildren(
    AuthLangIntranetRouteRouteChildren,
  )

interface AuthLangRouteChildren {
  AuthLangIntranetRouteRoute: typeof AuthLangIntranetRouteRouteWithChildren
  AuthLangAccessDeniedRoute: typeof AuthLangAccessDeniedRoute
  AuthLangAppRoute: typeof AuthLangAppRoute
  AuthLangChangePasswordRoute: typeof AuthLangChangePasswordRoute
  AuthLangForgotPasswordRoute: typeof AuthLangForgotPasswordRoute
  AuthLangLoginRoute: typeof AuthLangLoginRoute
  AuthLangResetPasswordRoute: typeof AuthLangResetPasswordRoute
}

const AuthLangRouteChildren: AuthLangRouteChildren = {
  AuthLangIntranetRouteRoute: AuthLangIntranetRouteRouteWithChildren,
  AuthLangAccessDeniedRoute: AuthLangAccessDeniedRoute,
  AuthLangAppRoute: AuthLangAppRoute,
  AuthLangChangePasswordRoute: AuthLangChangePasswordRoute,
  AuthLangForgotPasswordRoute: AuthLangForgotPasswordRoute,
  AuthLangLoginRoute: AuthLangLoginRoute,
  AuthLangResetPasswordRoute: AuthLangResetPasswordRoute,
}

const AuthLangRouteWithChildren = AuthLangRoute._addFileChildren(
  AuthLangRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLangRoute: typeof AuthLangRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLangRoute: AuthLangRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestAppRoute: typeof GuestAppRoute
  GuestIntranetRoute: typeof GuestIntranetRoute
  GuestLoginRoute: typeof GuestLoginRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestAppRoute: GuestAppRoute,
  GuestIntranetRoute: GuestIntranetRoute,
  GuestLoginRoute: GuestLoginRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

interface SiteLangRouteChildren {
  SiteLangSplatRoute: typeof SiteLangSplatRoute
  SiteLangAProposRoute: typeof SiteLangAProposRoute
  SiteLangBlogRoute: typeof SiteLangBlogRoute
  SiteLangConfidentialiteRoute: typeof SiteLangConfidentialiteRoute
  SiteLangContactRoute: typeof SiteLangContactRoute
  SiteLangCrowdfundingRoute: typeof SiteLangCrowdfundingRoute
  SiteLangEquipeRoute: typeof SiteLangEquipeRoute
  SiteLangEvenementsRoute: typeof SiteLangEvenementsRoute
  SiteLangFaqRoute: typeof SiteLangFaqRoute
  SiteLangHabitatRoute: typeof SiteLangHabitatRoute
  SiteLangImpactRoute: typeof SiteLangImpactRoute
  SiteLangMentionsLegalesRoute: typeof SiteLangMentionsLegalesRoute
  SiteLangPartenairesRoute: typeof SiteLangPartenairesRoute
  SiteLangPlanDuSiteRoute: typeof SiteLangPlanDuSiteRoute
  SiteLangPresseRoute: typeof SiteLangPresseRoute
  SiteLangSoutenirRoute: typeof SiteLangSoutenirRoute
  SiteLangSponsoringRoute: typeof SiteLangSponsoringRoute
  SiteLangVoyageRoute: typeof SiteLangVoyageRoute
  SiteLangIndexRoute: typeof SiteLangIndexRoute
  SiteLangLeVanSlugRoute: typeof SiteLangLeVanSlugRoute
  SiteLangLeVanIndexRoute: typeof SiteLangLeVanIndexRoute
}

const SiteLangRouteChildren: SiteLangRouteChildren = {
  SiteLangSplatRoute: SiteLangSplatRoute,
  SiteLangAProposRoute: SiteLangAProposRoute,
  SiteLangBlogRoute: SiteLangBlogRoute,
  SiteLangConfidentialiteRoute: SiteLangConfidentialiteRoute,
  SiteLangContactRoute: SiteLangContactRoute,
  SiteLangCrowdfundingRoute: SiteLangCrowdfundingRoute,
  SiteLangEquipeRoute: SiteLangEquipeRoute,
  SiteLangEvenementsRoute: SiteLangEvenementsRoute,
  SiteLangFaqRoute: SiteLangFaqRoute,
  SiteLangHabitatRoute: SiteLangHabitatRoute,
  SiteLangImpactRoute: SiteLangImpactRoute,
  SiteLangMentionsLegalesRoute: SiteLangMentionsLegalesRoute,
  SiteLangPartenairesRoute: SiteLangPartenairesRoute,
  SiteLangPlanDuSiteRoute: SiteLangPlanDuSiteRoute,
  SiteLangPresseRoute: SiteLangPresseRoute,
  SiteLangSoutenirRoute: SiteLangSoutenirRoute,
  SiteLangSponsoringRoute: SiteLangSponsoringRoute,
  SiteLangVoyageRoute: SiteLangVoyageRoute,
  SiteLangIndexRoute: SiteLangIndexRoute,
  SiteLangLeVanSlugRoute: SiteLangLeVanSlugRoute,
  SiteLangLeVanIndexRoute: SiteLangLeVanIndexRoute,
}

const SiteLangRouteWithChildren = SiteLangRoute._addFileChildren(
  SiteLangRouteChildren,
)

interface SiteRouteChildren {
  SiteLangRoute: typeof SiteLangRouteWithChildren
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteLangRoute: SiteLangRouteWithChildren,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  LlmsChar91DotChar93txtRoute: LlmsChar91DotChar93txtRoute,
  RobotsChar91DotChar93txtRoute: RobotsChar91DotChar93txtRoute,
  SitemapChar91DotChar93xmlRoute: SitemapChar91DotChar93xmlRoute,
  ApiDataChar91DotChar93jsonRoute: ApiDataChar91DotChar93jsonRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
